{
 "title": "Sample Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Application Latency over 5m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(sample_service_request_duration_seconds_bucket[5m]))) by (exported_endpoint)\n",
     "legendFormat": "__auto",
     "operation": "/api/users/<int:user_id>",
     "service": "sample-service"
    }
   ]
  },
  {
   "title": "Error Budget Slow Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(sample_service_requests_total{status=~\"5..\"}[5m]))\n  /\n  sum(rate(sample_service_requests_total[5m]))\n) > (0.01 * 2)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error requests error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sample_service_requests_total{status=\"500\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per endpoint over 5m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(sample_service_requests_total{exported_endpoint=~\"/api/.*\"}[5m])) by (exported_endpoint),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"monitoring\",pod=~\"sample-service.*\"}",
     "legendFormat": "__auto",
     "operation": "/api/users",
     "service": "sample-service"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"monitoring\",resource=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"monitoring\",pod=~\"sample-service.*\"}[5m])",
     "legendFormat": "__auto",
     "operation": "/api/users",
     "service": "sample-service"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"monitoring\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sample_service_up", "legendFormat": "__auto" }
   ]
  }
 ]
}