
apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    queue: {}
    output.elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      protocol: "https"
      ssl.certificate_authorities: ["/usr/share/apm-server/config/certs/ca.crt"]
replicas: 1


extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password


extraVolumeMounts:
  - name: elastic-certificates
    mountPath: /usr/share/apm-server/config/certs
    readOnly: true

extraVolumes:
  - name: elastic-certificates
    secret:
      secretName: elasticsearch-master-certs


image: "docker.elastic.co/apm/apm-server"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

# securityContext:
#   runAsUser: 0 
#   runAsGroup: 0
#   fsGroup: 0
