# Prometheus Operator Configuration
# This will install the Prometheus Operator and basic monitoring stack

# Use the official kube-prometheus-stack chart
kube-prometheus-stack:
  # Prometheus configuration
  prometheus:
    prometheusSpec:
      retention: 7d
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ""
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  
  # Grafana configuration (we'll use this for dashboards)
  grafana:
    enabled: true
    adminPassword: admin
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  
  # Alertmanager configuration
  alertmanager:
    enabled: true
    alertmanagerSpec:
      retention: 120h
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: ""
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
  
  # Node Exporter
  nodeExporter:
    enabled: true
  
  # Kube State Metrics
  kubeStateMetrics:
    enabled: true
  
  # Prometheus Node Exporter
  prometheus-node-exporter:
    enabled: true 