apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-apply
  namespace: obs
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        workingDir: /workspace
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Cloning repository..."
          git clone https://github.com/jonspandorf/sre-monitoring-challenge.git
          cd sre-monitoring-challenge/terraform
          
          echo "Initializing Terraform..."
          terraform init
          
          echo "Planning deployment..."
          terraform plan -var-file=vars.tfvars
          
          echo "Applying configuration..."
          terraform apply -var-file=vars.tfvars -auto-approve
          
          echo "Showing outputs..."
          terraform output
        env:
        - name: TF_VAR_ES_USERNAME
          value: "elastic"
        - name: TF_VAR_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              namespace: obs
              key: password
      restartPolicy: Never
  backoffLimit: 2
