storage:
  type: elasticsearch
  elasticsearch:
    extraEnv: 
      - name: ES_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: username
      - name: ES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password
    scheme: https
    host: elasticsearch-master
    port: 9200
    tls:
      enabled: true
      secretName: elasticsearch-master-certs
      # mountPath: /es-tls/ca.crt
      subPath: ca.crt

    user: $(ES_USERNAME)
    password: $(ES_PASSWORD)
    indexPrefix: jaeger
    # useAlias: true
    # sniffer: false

provisionDataStore:
  elasticsearch: false
  cassandra: false

collector:
  enabled: true
  replicaCount: 1
  service:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318


query:
  enabled: true
  service:
    type: ClusterIP

agent:
  enabled: true

allInOne:
  enabled: false

ingester:
  enabled: false


