mode: deployment
image:
  repository: "otel/opentelemetry-collector-contrib"
  tag: "latest"

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

    filelog:
      include: [/var/log/containers/**/*.log]
      start_at: beginning
      operators:
        - type: json_parser
          id: parse_json
          timestamp:
            parse_from: attributes.time
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        - type: move
          from: attributes.log
          to: body

  processors:
    batch:
      send_batch_size: 10000
      timeout: 10s
      send_batch_max_size: 11000

  exporters:
    otlp/elasticapm:
      endpoint: "http://apm-server-apm-server.elk:8200"
      tls:
        insecure: true
    otlp/jaeger:
      endpoint: "jaeger-collector.elk:4317"
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [batch]
        exporters: [otlp/elasticapm]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/elasticapm]  # You can remove if you’re not sending metrics
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/elasticapm,otlp/jaeger]

extraVolumes:
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
      type: Directory
  - name: varlog 
    hostPath:
      path: /var/log
      type: Directory

extraVolumeMounts:
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: varlog
    mountPath: /var/log
    readOnly: true

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Security context to access log files
securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Service configuration
service:
  type: ClusterIP
